server:
  port: ${SERVER_PORT}

spring:
  application:
    name: smart-expense-tracker
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # change to 'validate' or 'none' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      indent_output: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework: INFO
    com.gyarsilalsolanki011.expense: DEBUG

jwt:
  secret:
    key: ${JWT_SECRET}
  expiration:
    time: ${JWT_EXPIRATION_MS}